// <auto-generated />
namespace ReHouse.Utils.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adminfb1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adminfb1));
        
        string IMigrationMetadata.Id
        {
            get { return "201711170839243_adminfb1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
